# Generated by Django 4.1 on 2022-08-29 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0010_basket"),
    ]

    operations = [
        migrations.RenameField(
            model_name="basket",
            old_name="device_id",
            new_name="device",
        ),
        migrations.RenameField(
            model_name="basket",
            old_name="user_id",
            new_name="user",
        ),
    ]
