# Generated by Django 4.1 on 2022-08-29 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0011_rename_device_id_basket_device_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basket",
            name="qty",
        ),
    ]
